# Deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: ashif8984/my-app:7d542096625063705b0778c67861d745008a3a52
        ports:
        - containerPort: 3000