# Deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: ashif8984/my-app:954242c36b5d31c117479a5e4292a087aa62dd6c
        ports:
        - containerPort: 3000