# Deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: ashif8984/my-app:7a941a5d6da27875a92663c0b6fbdbd056ff37fc
        ports:
        - containerPort: 3000